### ISSUE TITLE
Can't find Wu tang artist's information and tracks

### ISSUE THREAD

**Issue by skuill** [skuill/ConcertBuddy#28]
**Logs:**

2022-02-01 09:49:27.143 +00:00 [Debug] [MusicSearcher.MusicSearcherClient] Find artists for [Wu tang]: Wu‐Tang Clan [score: 100]; Wu tang Switch [score: 88]; Wu-Tang Killa Bees [score: 84]; Wu-Tang Yellow Jacketz [score: 79]; Ghostface Killah [score: 58]
2022-02-01 09:49:31.823 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.ArtistCommand] Handle [/artist] command: [/artist 0febdcf7-4e1f-4661-9493-b40427de2c13]
2022-02-01 09:49:32.159 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 118
2022-02-01 09:49:35.585 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TopCommand] Handle [/top] command: [/top track 0febdcf7-4e1f-4661-9493-b40427de2c13]
2022-02-01 09:49:35.826 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 118
2022-02-01 09:49:35.834 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist [] from Spotify.
System.ArgumentException: String is empty or null (Parameter 'query')
   at SpotifyAPI.Web.Ensure.ArgumentNotNullOrEmptyString(String value, String name)
   at SpotifyAPI.Web.SearchRequest..ctor(Types type, String query)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 199
2022-02-01 09:49:35.839 +00:00 [Error] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TopCommand] Can't find top tracks for artist [] with mbid [0febdcf7-4e1f-4661-9493-b40427de2c13]
2022-02-01 09:49:45.565 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.SetlistsCommand] Handle [/setlists] command: [/setlists 1 0 0febdcf7-4e1f-4661-9493-b40427de2c13]
2022-02-01 09:49:51.968 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.SetlistCommand] Handle [/setlist] command: [/setlist 0febdcf7-4e1f-4661-9493-b40427de2c13 438d4b2f]
2022-02-01 09:50:01.600 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Shame on a Nigga]
2022-02-01 09:50:02.146 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 118
2022-02-01 09:50:02.453 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shame on a Nigga] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 09:50:02.999 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shame on a Nigga] for artist [] from Yandex.
System.Exception: Can't get track [Shame on a Nigga] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162
2022-02-01 09:50:39.299 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Shimmy Shimmy Ya]
2022-02-01 09:50:39.535 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 118
2022-02-01 09:50:39.814 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 09:50:40.215 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Yandex.
System.Exception: Can't get track [Shimmy Shimmy Ya] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162
2022-02-01 09:51:06.827 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Shimmy Shimmy Ya]
2022-02-01 09:51:07.066 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 118
2022-02-01 09:51:07.219 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 09:51:07.429 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Yandex.
System.Exception: Can't get track [Shimmy Shimmy Ya] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162
2022-02-01 09:51:25.627 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Shimmy Shimmy Ya]
2022-02-01 09:51:25.869 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 131
2022-02-01 09:51:26.040 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 09:51:26.269 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shimmy Shimmy Ya] for artist [] from Yandex.
System.Exception: Can't get track [Shimmy Shimmy Ya] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162
2022-02-01 09:51:29.682 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Shame on a Nigga]
2022-02-01 09:51:29.936 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 131
2022-02-01 09:51:30.095 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shame on a Nigga] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 09:51:30.466 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Shame on a Nigga] for artist [] from Yandex.
System.Exception: Can't get track [Shame on a Nigga] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162
2022-02-01 10:00:46.354 +00:00 [Debug] [ConcertBuddy.ConsoleApp.TelegramBot.Command.TrackCommand] Handle [/track] command: [/track 0febdcf7-4e1f-4661-9493-b40427de2c13 Gravel Pit]
2022-02-01 10:00:46.716 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist by mbid [0febdcf7-4e1f-4661-9493-b40427de2c13] from LastFM
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.GetSpotifyArtist(String artistName) in /src/MusicSearcher/MusicSearcherClient.cs:line 378
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in /src/MusicSearcher/MusicSearcherClient.cs:line 131
2022-02-01 10:00:46.992 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Gravel Pit] for artist [] from Spotify.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MusicSearcher.MusicSearcherClient.SearchSpotifyTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 184
2022-02-01 10:00:47.305 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't search track [Gravel Pit] for artist [] from Yandex.
System.Exception: Can't get track [Gravel Pit] for artist [] from Yandex.
   at MusicSearcher.MusicSearcherClient.SearchYandexTrack(String artistName, String trackName) in /src/MusicSearcher/MusicSearcherClient.cs:line 162

**Comment by skuill** [comment]
Maybe because of #29

**Comment by skuill** [comment]
1) #29 fix helped here
2) In some artist names (for example: [Wu‐Tang Clan](https://musicbrainz.org/artist/0febdcf7-4e1f-4661-9493-b40427de2c13)) there is the following hyphen -> Unicode: [(U+2010)]
but it should be the following hyphen -> Unicode: [(U+002D)]
