### ISSUE TITLE
Map properly MusicBrainz to Spotify track while searching

### ISSUE THREAD

**Issue by skuill** [skuill/ConcertBuddy#29]
Spotify don't use MBID and use it's own ID for artists/tracks.
We can't compare artistName. For example for artist "ноганно" actual spotify name is "noganno".
Now we return first result from searching artist/track.

For example (false search):
![image](https://user-images.githubusercontent.com/19705282/152546544-b50bb2f3-56db-4383-8543-767444353a67.png)

**Comment by skuill** [comment]
1) Search with Market set does not work:
`var searchArtist = await _spotifyClient.Search.Item(new SearchRequest(SearchRequest.Types.Artist, name) { Market = "RU"});`
Error logs:
`2022-10-23 13:58:15.933 +00:00 [Error] [MusicSearcher.MusicSearcherClient] Can't get artist from music service [SpotifyServiceClient]
SpotifyAPI.Web.APIException: Unlaunched market
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at MusicSearcher.MusicService.Spotify.SpotifyServiceClient.SearchArtistByName(String name) in C:\Projects\ConcertBuddy\ConcertBuddy\MusicSearcher\MusicService\Spotify\SpotifyServiceClient.cs:line 84
   at MusicSearcher.MusicSearcherClient.SearchArtistByMBID(String artistMBID) in C:\Projects\ConcertBuddy\ConcertBuddy\MusicSearcher\MusicSearcherClient.cs:line 139`

2. Search with country ISO code in query does not work:
`var searchArtist = await _spotifyClient.Search.Item(new SearchRequest(SearchRequest.Types.Artist, name + " RU"));` 

**But search with area (country) full name work!:**
`var searchArtist = await _spotifyClient.Search.Item(new SearchRequest(SearchRequest.Types.Artist, name + " Russia"));`

**Comment by skuill** [comment]
Workaround: Try to return first artist after search with the same name. Otherwise return first from a collection
